// Faithful TypeScript port of info/data/price_model_reference.py -> parametric_quote().
// Money is computed here, never by an LLM. tests/unit/quote.parity.test.ts proves 100% equality with
// the Python output (tests/fixtures/parity.json, generated by scripts/gen-parity.py).
// The model JSON is a byte copy of info/data/price_model.json (scripts/sync-data.mjs keeps it in sync).
import model from "../data/price_model.json";
import { roundHalfEven, roundHalfEvenN } from "./pyround";

export const SCOPES = [
  "risers_complete",
  "risers_water_only",
  "risers_sewer_only",
  "risers_kitchen_only",
  "heating_risers",
] as const;
export type Scope = (typeof SCOPES)[number];

export const OPTIONS = ["opt_sound_fire_wrap", "opt_new_towel_rail"] as const;
export type QuoteOption = (typeof OPTIONS)[number];

export type Level = "low" | "base" | "high";
export const LEVELS: readonly Level[] = ["low", "base", "high"];
type Rate = { low: number; base: number; high: number };

export const PRICE_MODEL_VERSION: string = model.version;
export const VAT_RATE: number = model.vat_rate;
const R = model.parametric.unit_rates as unknown as Record<string, Rate>;
const SCHEDULE = model.parametric.schedule;
const MONTHS: number[] = model.parametric.installments.months_options;

export interface QuoteInput {
  floors: number;
  apartments: number;
  stairwells: number;
  scope?: Scope;
  horizontals?: boolean;
  sewer_outlet?: boolean;
  pump_station?: boolean;
  options?: readonly QuoteOption[];
}

export interface ParametricQuote {
  range: Record<Level, { net: number; gross: number }>;
  per_apartment_gross: number;
  /** Ported for parity only. NEVER spoken or shown (no instalments in the voice demo). */
  monthly_per_apartment_gross: Record<string, number>;
  riser_sets_estimate: number;
  per_riser_set_net: number;
  /** Ported for parity only. NEVER spoken or shown (no working-day estimates). */
  working_days_estimate: number;
  crews_assumed: number;
}

function rate(key: string): Rate {
  const r = R[key];
  if (!r) throw new Error(`unknown rate ${key}`);
  return r;
}

/** Exact port of parametric_quote(floors, apartments, stairwells, scope, horizontals, sewer_outlet, pump_station, options). */
export function parametricQuote(input: QuoteInput): ParametricQuote {
  const {
    floors,
    apartments,
    stairwells,
    scope = "risers_complete",
    horizontals = true,
    sewer_outlet = false,
    pump_station = false,
    options = [],
  } = input;
  if (!(SCOPES as readonly string[]).includes(scope)) throw new Error(`unknown scope ${scope}`);
  for (const o of options) if (!(OPTIONS as readonly string[]).includes(o)) throw new Error(`unknown option ${o}`);
  if (!(floors > 0) || !(apartments > 0)) throw new RangeError("floors and apartments must be > 0");

  const vatFactor = 1 + VAT_RATE; // same double as Python's (1 + VAT)
  const range = {} as Record<Level, { net: number; gross: number }>;
  for (const level of LEVELS) {
    let net = rate("mobilisation")[level];
    net += stairwells * rate("fixed_per_stairwell")[level];
    net += apartments * rate(scope)[level];
    if (horizontals) net += stairwells * rate("basement_horizontals")[level];
    if (sewer_outlet) net += stairwells * rate("sewer_outlet")[level];
    if (pump_station) net += rate("pump_station")[level];
    for (const opt of options) net += apartments * rate(opt)[level];
    range[level] = { net: roundHalfEven(net), gross: roundHalfEven(net * vatFactor) };
  }
  const baseGross = range.base.gross;
  const sets = Math.max(1, roundHalfEven(apartments / floors));
  const crews = SCHEDULE.default_crews;
  const days = Math.ceil(apartments / (SCHEDULE.bathrooms_per_crew_day * crews));
  const monthly: Record<string, number> = {};
  for (const m of MONTHS) monthly[String(m)] = roundHalfEvenN(baseGross / apartments / m, 2);
  return {
    range,
    per_apartment_gross: roundHalfEven(baseGross / apartments),
    monthly_per_apartment_gross: monthly,
    riser_sets_estimate: sets,
    per_riser_set_net: roundHalfEven(range.base.net / sets),
    working_days_estimate: days,
    crews_assumed: crews,
  };
}

/** Labels for scopes/options, straight from price_model.json (RU/LV/EN where present). */
export function scopeLabel(key: Scope | QuoteOption, lang: "ru" | "lv" | "en"): string {
  const label = (rate(key) as unknown as { label?: Record<string, string> }).label ?? {};
  return label[lang] ?? label.ru ?? key;
}
