// Generates the ElevenLabs webhook tools from the zod contract (src/contract) and syncs them to the workspace.
//   node scripts/gen-tools.ts            create/update the workspace secret + 7 tools, write elevenlabs/tools.json
//   node scripts/gen-tools.ts --dry      write elevenlabs/tools.json only (placeholders for ids), no API calls
// The x-scg-key header value is {secret_id} of the workspace secret that holds SCG_TOOL_KEY (read from the env, never printed).
// conversation_id is bound to system__conversation_id by the contract (dynamic_variable), so the model never fills it.
import { el } from './el/api.ts';
import { cfg, ensureToolSecret, listAllTools, loadContract, p, readJson, writeJson } from './el/common.ts';
import { existsSync } from 'node:fs';

const dry = process.argv.includes('--dry');
const c = cfg();
const { toElevenLabsTool, TOOL_NAMES } = await loadContract();
const secretId = dry ? '{secret_id}' : await ensureToolSecret(c.tool_secret_name);
const prev = existsSync(p('elevenlabs', 'tools.json')) ? readJson(p('elevenlabs', 'tools.json')) : { tools: {} };
const existing = dry ? [] : await listAllTools();
const out: Record<string, any> = {};
for (const n of TOOL_NAMES) {
  const t = toElevenLabsTool(n, { baseUrl: c.worker_url, secretId });
  // A property bound to a dynamic variable must not carry a description (mutually exclusive on the platform).
  for (const prop of Object.values<any>(t.api_schema.request_body_schema.properties)) {
    if (prop.dynamic_variable) delete prop.description;
    if (prop.items && !prop.items.description) prop.items.description = `One of: ${(prop.items.enum ?? []).join(', ') || 'values as described above'}.`; // array items need their own description
  }
  const tool_config = { type: 'webhook', ...t, force_pre_tool_speech: false, pre_tool_speech: 'auto', tool_error_handling_mode: 'auto' };
  let id: string | undefined = prev.tools?.[n]?.id;
  if (!dry) {
    const hit = existing.find((x) => x.tool_config?.name === n) ?? existing.find((x) => x.id === id);
    if (hit) { id = hit.id; await el('PATCH', `/v1/convai/tools/${id}`, { tool_config }); console.log(`${n}: updated ${id}`); }
    else { const r = await el('POST', '/v1/convai/tools', { tool_config }); id = r.id; console.log(`${n}: created ${id}`); }
  }
  out[n] = { id: id ?? null, config: tool_config };
}
writeJson(p('elevenlabs', 'tools.json'), { _note: 'GENERATED by scripts/gen-tools.ts from src/contract/schemas.ts. Do not edit. Ids only; the key lives in the workspace secret.', worker_url: c.worker_url, secret_id: secretId, tools: out });
console.log(`tools.json written (${TOOL_NAMES.length} tools, ${dry ? 'dry' : 'synced'})`);
